version: "3.8"
services:
  forgePg:
    image: postgres:13-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=forgePg
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
